AWSTemplateFormatVersion: 2010-09-09-OC

Parameters:

  aggregationRegions: 
    Type: List<String>

Resources:
      
  Hub:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: Community::SecurityHub::Hub
    OrganizationBinding: !Ref AllBinding
    Properties:
      EnableDefaultStandards: false
      ControlFindingGenerator: SECURITY_CONTROL # change to STANDARD_CONTROL to turn off consolidated findings.
      
  Standards:
    Type: Community::SecurityHub::Standards
    DependsOn: Hub
    OrganizationBinding: !Ref AllBinding
    Properties:
      CIS14: ENABLED
      AFSBP: ENABLED
      CIS12: DISABLED
      PCIDSS: DISABLED

  FindingAggregation:
    Type: Community::SecurityHub::FindingAggregation
    DependsOn: Hub
    OrganizationBinding: !Ref PrimaryRegionBinding
    Properties:
      RegionLinkingMode: SPECIFIED_REGIONS
      Regions: !Ref aggregationRegions

